
[program:ha-cache]
command=python3 /usr/local/bin/ha-tachyon-cache-worker.py
user=root
autostart=true
autorestart=true
startsecs=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
